### ISSUE TITLE
Missing Semicolon

### ISSUE THREAD

**Issue by Svaught598** [chr15m/minimal-stylesheet#6]
Hi! 

I use this stylesheet all the time! I've noticed that every time I pull it down I have to add a missing semicolon. 

I'll probably submit a pull request at some point, just wanted to leave an issue for posterity.

**Comment by chr15m** [comment]
Excellent, thanks for the heads up! Which semi colon?

**Comment by svaught599** [comment]
https://github.com/chr15m/minimal-stylesheet/blob/b8bc8bdcc7d44c4b92e20ea47866c6a74dd75566/minimal-inputs.css#L110
